<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI44zfoY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI44zfoY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI44zfoY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI44zfoY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI44zfoY\App_KernelDevDebugContainer([
    'container.build_hash' => 'I44zfoY',
    'container.build_id' => 'cf934153',
    'container.build_time' => 1615209953,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI44zfoY');
