<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8n1NPQ9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8n1NPQ9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8n1NPQ9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8n1NPQ9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8n1NPQ9\App_KernelDevDebugContainer([
    'container.build_hash' => '8n1NPQ9',
    'container.build_id' => '4c2b6a1b',
    'container.build_time' => 1614961129,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8n1NPQ9');
